# Generated by Django 3.0.7 on 2020-06-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200605_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.SubTask'),
        ),
    ]
