# Generated by Django 3.0.7 on 2020-06-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200605_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Repository'),
        ),
    ]
